# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nest-os
description: Custom Secureblue image
base-image: ghcr.io/wayblueorg/river
image-version: 41

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/secureblue/bubblejail/repo/fedora-%OS_VERSION%/secureblue-bubblejail-fedora-%OS_VERSION%.repo
      - https://repo.secureblue.dev/secureblue.repo
      - https://copr.fedorainfracloud.org/coprs/secureblue/branding/repo/fedora-%OS_VERSION%/secureblue-branding-fedora-%OS_VERSION%.repo
    install:
      - headsetcontrol
      - trivalent
      - secureblue-logos
      - mediainfo
      - bubblejail
      - usbguard-notifier
      - usbguard
      - setroubleshoot
      - setools
      - fscrypt
      - vim
      - wl-clipboard
      - alsa-firmware
      - google-noto-fonts-all
      - ripgrep
      - lf
      - neovim
    remove:
      - fedora-logos
      - firefox
      - firefox-langpacks
      - fuse
      - fedora-chromium-config
      - fedora-flathub-remote
      - passim
      - sudo
      - sudo-python-plugin
      - toolbox

  - type: default-flatpaks
    notify: true 
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - from: ghcr.io/secureblue/secureblue
    include:
      - modules/hardening
      - modules/security
      - modules/sdboot
      - modules/workstation
      - modules/toolbox
